---
replicaCount: 1

image:
  repository: tutum/hello-world
  pullPolicy: IfNotPresent

deploymentAnnotations:
  {}
  # https://kubernetes.io/blog/2021/04/20/annotating-k8s-for-humans/
  # a8r.io/owner: john doe
  # a8r.io/chat: #engineering
  # a8r.io/description: my beatiful service

livenessProbe:
  {}
  # httpGet:
  #   path: /healthz
  #   port: 8080
  #   httpHeaders:
  #     - name: Custom-Header
  #       value: Awesome
  # initialDelaySeconds:
  # failureThreshold: 1
  # periodSeconds: 60

readinessProbe:
  {}
  # httpGet:
  #   path: /healthz
  #   port: 8080
  #   httpHeaders:
  #     - name: Custom-Header
  #       value: Awesome
  # initialDelaySeconds: 50
  # failureThreshold: 1
  # periodSeconds: 50

env:
  []
  # - name: SAMPLE_PLAIN_TEXT_ENV
  #   value: "Hello World"
  # - name: SAMPLE_INT_ENV
  #   value: 420

vaultSecret:
  enabled: false
  # vault:
  #   address: https://my.vault.host
  #   role: my-vault-role
  #   path: my/secret/path
  # data:
  #   SAMPLE_VAULT_SECRET: ${my/secret/path#key}

opConnect:
  enabled: false
  # item:
  #   path:
  #   name:

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  environment: staging
  subdomain: http-api
  auth: false
  # annotations:

resources:
  requests: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

serviceAccount:
  create: true
  annotations:
    {}
    # eks.amazonaws.com/role-arn: arn:aws:iam::<AWS_ACCOUNT_ID>:role/<ROLE_NAME>
