replicaCount: 1

image:
  repository: tutum/hello-world
  pullPolicy: IfNotPresent

healthcheck:
  enabled: false
  # path: /
  # delay: 10

env:
  # - name: SAMPLE_PLAINT_TEXT_ENV
  #   value: "Hello World"

vaultSecret:
  enabled: false
  # vault:
  #   address: https://my.vault.host
  #   role: my-vault-role
  #   path: my/secret/path
  # data:
  #   SAMPLE_VAULT_SECRET: ${my/secret/path#key}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  environment: staging
  subdomain: http-api
  auth: false
  # annotations:

resources:
  requests: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
