replicaCount: 1

image:
  repository: tutum/hello-world
  pullPolicy: IfNotPresent


env:
  # - name: SAMPLE_PLAINT_TEXT_ENV
  #   value: "Hello World"
livenessProbe:
  {}
  # httpGet:
  #   path: /healthz
  #   port: 8080
  #   httpHeaders:
  #     - name: Custom-Header
  #       value: Awesome
  # initialDelaySeconds:
  # failureThreshold: 1
  # periodSeconds: 60

readinessProbe:
  {}
  # httpGet:
  #   path: /healthz
  #   port: 8080
  #   httpHeaders:
  #     - name: Custom-Header
  #       value: Awesome
  # initialDelaySeconds: 50
  # failureThreshold: 1
  # periodSeconds: 50
vaultSecret:
  enabled: false
  # vault:
  #   address: https://my.vault.host
  #   role: my-vault-role
  #   path: my/secret/path
  # data:
  #   SAMPLE_VAULT_SECRET: ${my/secret/path#key}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  environment: staging
  subdomain: http-api
  auth: false
  # annotations:

resources:
  requests: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
