{{- $fullName := include "http-app.fullname" . -}}

{{- if and .Values.vaultSecret.enabled .Values.vaultSecret.data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-secret
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    vault.security.banzaicloud.io/vault-addr: {{ .Values.vaultSecret.vault.address }}
    vault.security.banzaicloud.io/vault-role: {{ .Values.vaultSecret.vault.role }}
    vault.security.banzaicloud.io/vault-path: {{ .Values.vaultSecret.vault.path }}
stringData:
  {{ range $key, $value := .Values.vaultSecret.data }}
  {{ $key }}: {{ $value }}
  {{ end }}
{{- end }}